-- Munsiq Platform Seed Data

-- This script should be run once per tenant schema after DDL.

-- 1. ROLES
-- These are global and should be in the public schema, but are included here for completeness.
INSERT INTO public.roles (name) VALUES
("SuperAdmin"),
("Admin"),
("PropertyManager"),
("Tenant"),
("Accountant"),
("MaintenanceTech");

-- 2. USERS (Example for one tenant)
-- Passwords should be properly hashed by the application.
-- Assuming role IDs are known.
INSERT INTO users (role_id, name, email, password_hash) VALUES
((SELECT id FROM public.roles WHERE name = "Admin"), "Abdullah Al-Amoudi", "abdullah@munsiq-demo.sa", "$2b$12$...."),
((SELECT id FROM public.roles WHERE name = "PropertyManager"), "Ahmed Al-Ghamdi", "ahmed@munsiq-demo.sa", "$2b$12$...."),
((SELECT id FROM public.roles WHERE name = "Accountant"), "Khalid Al-Zahrani", "khalid@munsiq-demo.sa", "$2b$12$...."),
((SELECT id FROM public.roles WHERE name = "MaintenanceTech"), "Fahad Khan", "fahad@munsiq-demo.sa", "$2b$12$....");

-- 3. PROPERTIES
INSERT INTO properties (name, address, latitude, longitude, type, status) VALUES
("Burj Al Yassmin", "Riyadh, Al Yassmin District", 24.8136, 46.6653, "residential", "ACTIVE"),
("Al Faisaliah Commercial Tower", "Riyadh, Olaya Street", 24.6872, 46.6826, "commercial", "ACTIVE");

-- 4. UNITS
INSERT INTO units (property_id, unit_number, status, annual_rent, bedrooms)
VALUES
((SELECT id FROM properties WHERE name = "Burj Al Yassmin"), "A-101", "VACANT", 45000.00, 3),
((SELECT id FROM properties WHERE name = "Burj Al Yassmin"), "A-102", "VACANT", 46000.00, 3),
((SELECT id FROM properties WHERE name = "Burj Al Yassmin"), "B-201", "OCCUPIED", 55000.00, 4),
((SELECT id FROM properties WHERE name = "Al Faisaliah Commercial Tower"), "OFFICE-301", "VACANT", 150000.00, 0);

-- 5. TENANTS (Example)
-- PII is encrypted by the app, so this is just illustrative.
INSERT INTO tenants (full_name_encrypted, national_id_encrypted, phone_number_encrypted, verification_status)
VALUES
("ENCRYPTED_DATA_SARA", "ENCRYPTED_DATA_SARA_ID", "ENCRYPTED_DATA_SARA_PHONE", "VERIFIED");

-- 6. CONTRACTS (Example for an occupied unit)
INSERT INTO contracts (unit_id, tenant_id, start_date, end_date, annual_rent, status, ejar_contract_id)
VALUES
((SELECT id FROM units WHERE unit_number = "B-201"), (SELECT id FROM tenants LIMIT 1), "2025-06-01", "2026-05-31", 55000.00, "ACTIVE", "EJAR-123456789");

-- 7. INSTALLMENTS (Example for the active contract)
-- This would be generated by the application.
INSERT INTO installments (contract_id, due_date, amount, status)
SELECT
    id AS contract_id,
    generate_series("2025-06-01"::date, "2026-05-01"::date, "1 month") AS due_date,
    55000.00 / 12 AS amount,
    "PENDING" AS status
FROM contracts WHERE ejar_contract_id = "EJAR-123456789";

-- Set past installments to PAID for demo purposes
UPDATE installments SET status = "PAID" WHERE due_date < NOW() - interval "2 month";

-- 8. INVOICES & PAYMENTS (Example for one paid installment)
WITH paid_installment AS (
    SELECT id FROM installments WHERE status = "PAID" LIMIT 1
)
INSERT INTO invoices (installment_id, status, amount, due_date, sadad_bill_number)
SELECT id, "PAID", 4583.33, due_date, "SADAD-" || substr(md5(random()::text), 0, 15)
FROM installments WHERE id = (SELECT id FROM paid_installment);

INSERT INTO payments (invoice_id, amount_paid, method, reference_number)
SELECT id, 4583.33, "SADAD", "SADAD-REF-" || substr(md5(random()::text), 0, 20)
FROM invoices WHERE installment_id = (SELECT id FROM paid_installment);

-- 9. MAINTENANCE_REQUESTS (Example)
INSERT INTO maintenance_requests (unit_id, tenant_id, description, priority, status)
VALUES
((SELECT id FROM units WHERE unit_number = "B-201"), (SELECT id FROM tenants LIMIT 1), "AC not cooling in master bedroom.", "HIGH", "NEW");
